import type { IntegrationProvider } from "@/src/types/fleet";

export type ConnectorKey =
  | "samsara"
  | "geotab"
  | "motive"
  | "fleetio"
  | "quickbooks"
  | "csv"
  | "rest_api"
  | "webhook";

export type ConnectorType =
  | "telematics"
  | "fleet_operations"
  | "accounting"
  | "import"
  | "rest_ingest"
  | "webhook";

export type ConnectorAuthType =
  | "oauth"
  | "api_key"
  | "bearer_token"
  | "webhook_secret"
  | "none";

export type ConnectorDefinition = {
  key: string;
  provider: IntegrationProvider | null;
  displayName: string;
  category: ConnectorOperationalCategory;
  providerType: ConnectorProviderType;
  connectorType: ConnectorType;
  authType: ConnectorAuthType;
  status: ConnectorStatus;
  description: string;
  primaryDataDomains: string[];
  capabilities: string[];
  syncDirection: ConnectorSyncDirection;
  connectionComplexity: ConnectorConnectionComplexity;
  recommendedFor: string[];
  version: string;
  supportsHistoricalSync: boolean;
  supportsPushWebhook: boolean;
  mappingObjectTypes: string[];
};

export type ConnectorStatus = "available" | "coming_soon";

export type ConnectorProviderType = "native" | "partner" | "custom" | "future";

export type ConnectorSyncDirection = "inbound" | "outbound" | "bidirectional";

export type ConnectorConnectionComplexity = "low" | "medium" | "high";

export type ConnectorOperationalCategory =
  | "fleet_telematics"
  | "fleet_management"
  | "dispatch_field_service"
  | "erp_accounting"
  | "hr_workforce"
  | "crm"
  | "operational_data_sources"
  | "custom_integrations";

export type ConnectorCategoryDefinition = {
  id: ConnectorOperationalCategory;
  label: string;
  description: string;
  coverageKey: string;
};

export const CONNECTED_SYSTEMS_CATEGORIES: readonly ConnectorCategoryDefinition[] = [
  {
    id: "fleet_telematics",
    label: "Fleet & Telematics",
    description:
      "Connect real-time vehicle telemetry for utilization, deadhead, travel time, and operational visibility.",
    coverageKey: "Fleet",
  },
  {
    id: "fleet_management",
    label: "Fleet Management",
    description:
      "Connect fleet assets, maintenance, inspections, and lifecycle systems to improve operational readiness.",
    coverageKey: "Fleet Mgmt",
  },
  {
    id: "dispatch_field_service",
    label: "Dispatch & Field Service",
    description:
      "Connect dispatch and field service systems to align jobs, schedules, technician status, and execution flow.",
    coverageKey: "Dispatch",
  },
  {
    id: "erp_accounting",
    label: "ERP & Accounting",
    description:
      "Connect financial systems to calculate revenue, contribution, branch performance, and operational profitability.",
    coverageKey: "ERP",
  },
  {
    id: "hr_workforce",
    label: "HR & Workforce",
    description:
      "Connect workforce systems to improve labor planning, certifications, operator availability, and scheduling intelligence.",
    coverageKey: "Payroll",
  },
  {
    id: "crm",
    label: "CRM",
    description:
      "Connect customer and account systems so operations can act on customer context, opportunities, and relationships.",
    coverageKey: "CRM",
  },
  {
    id: "operational_data_sources",
    label: "Operational Data Sources",
    description:
      "Universal ingestion channels for operational records from files, APIs, and webhook event streams.",
    coverageKey: "Data Sources",
  },
  {
    id: "custom_integrations",
    label: "Custom Integrations",
    description:
      "Enterprise extensibility for custom connectors, event ingestion, and future SDK-driven operational data exchange.",
    coverageKey: "Custom",
  },
] as const;

export const CONNECTOR_CATALOG: readonly ConnectorDefinition[] = [
  {
    key: "samsara",
    provider: "samsara",
    displayName: "Samsara",
    category: "fleet_telematics",
    providerType: "native",
    connectorType: "telematics",
    authType: "oauth",
    status: "available",
    description: "Vehicle telemetry, GPS history, and utilization signals from Samsara.",
    primaryDataDomains: ["GPS", "Truck status", "Route telemetry"],
    capabilities: ["Real-time location", "Utilization", "Deadhead analysis", "Historical sync"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Fleet-first operations", "Live dispatch visibility"],
    version: "v1.0",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["trucks", "jobs", "sites"],
  },
  {
    key: "geotab",
    provider: "geotab",
    displayName: "Geotab",
    category: "fleet_telematics",
    providerType: "partner",
    connectorType: "telematics",
    authType: "api_key",
    status: "available",
    description: "Telematics integration for GPS, fleet utilization, and trip intelligence.",
    primaryDataDomains: ["GPS", "Trips", "Vehicle telemetry"],
    capabilities: ["Location ingest", "Trip telemetry", "Historical sync"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Multi-branch fleets", "Utilization tracking"],
    version: "v1.0",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["trucks", "jobs", "sites"],
  },
  {
    key: "motive",
    provider: "motive",
    displayName: "Motive",
    category: "fleet_telematics",
    providerType: "partner",
    connectorType: "telematics",
    authType: "oauth",
    status: "available",
    description: "Motive telematics for real-time dispatch context and fleet analytics.",
    primaryDataDomains: ["GPS", "Truck events", "Driver telemetry"],
    capabilities: ["Live location", "Driver context", "Historical sync"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Mixed fleets", "Operational command centers"],
    version: "v1.0",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["trucks", "jobs", "sites"],
  },
  {
    key: "verizon_connect",
    provider: null,
    displayName: "Verizon Connect",
    category: "fleet_telematics",
    providerType: "future",
    connectorType: "telematics",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned telematics connector for enterprise fleet telemetry and route visibility.",
    primaryDataDomains: ["GPS", "Trips", "Vehicle events"],
    capabilities: ["Live location", "Historical sync", "Route telemetry"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Enterprise telematics standardization"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["trucks", "jobs", "sites"],
  },
  {
    key: "azuga",
    provider: null,
    displayName: "Azuga",
    category: "fleet_telematics",
    providerType: "future",
    connectorType: "telematics",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned connector for Azuga location and fleet utilization telemetry.",
    primaryDataDomains: ["GPS", "Driver behavior", "Trips"],
    capabilities: ["Location ingest", "Telemetry visibility"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Regional fleets", "Live utilization signals"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["trucks", "jobs", "sites"],
  },
  {
    key: "fleetio",
    provider: "fleetio",
    displayName: "Fleetio",
    category: "fleet_management",
    providerType: "native",
    connectorType: "fleet_operations",
    authType: "api_key",
    status: "available",
    description: "Fleet asset and maintenance system data for operational planning context.",
    primaryDataDomains: ["Fleet assets", "Maintenance state", "Vehicle metadata"],
    capabilities: ["Asset sync", "Maintenance context", "Historical sync"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Fleet lifecycle management", "Maintenance-aware dispatch"],
    version: "v1.0",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["trucks", "operators", "jobs"],
  },
  {
    key: "whip_around",
    provider: null,
    displayName: "Whip Around",
    category: "fleet_management",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "api_key",
    status: "coming_soon",
    description: "Planned DVIR and inspection data integration for fleet readiness.",
    primaryDataDomains: ["Inspections", "Compliance", "Fleet condition"],
    capabilities: ["Inspection ingest", "Condition visibility"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Compliance-heavy fleets"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["trucks", "operators"],
  },
  {
    key: "assetworks",
    provider: null,
    displayName: "AssetWorks",
    category: "fleet_management",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned enterprise asset lifecycle connector for fleet and equipment systems.",
    primaryDataDomains: ["Asset lifecycle", "Maintenance", "Inspection"],
    capabilities: ["Asset sync", "Lifecycle context"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Enterprise fleet programs"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["trucks", "equipment"],
  },
  {
    key: "servicetitan",
    provider: null,
    displayName: "ServiceTitan",
    category: "dispatch_field_service",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned dispatch and field service connector for job and technician orchestration.",
    primaryDataDomains: ["Jobs", "Schedules", "Technicians"],
    capabilities: ["Job sync", "Status ingest", "Schedule context"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Field service operations"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: true,
    mappingObjectTypes: ["jobs", "operators", "sites", "customers"],
  },
  {
    key: "buildops",
    provider: null,
    displayName: "BuildOps",
    category: "dispatch_field_service",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned commercial field service connector for dispatch and execution data.",
    primaryDataDomains: ["Dispatch", "Jobs", "Technicians"],
    capabilities: ["Job ingest", "Technician state", "Schedule sync"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Commercial contractors"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: true,
    mappingObjectTypes: ["jobs", "operators", "sites"],
  },
  {
    key: "fieldpulse",
    provider: null,
    displayName: "FieldPulse",
    category: "dispatch_field_service",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned connector for field scheduling, work status, and customer jobs.",
    primaryDataDomains: ["Jobs", "Schedules", "Customers"],
    capabilities: ["Job sync", "Customer context"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Mid-market field service"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: true,
    mappingObjectTypes: ["jobs", "customers", "sites", "operators"],
  },
  {
    key: "jobber",
    provider: null,
    displayName: "Jobber",
    category: "dispatch_field_service",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned connector for service jobs, customer records, and schedule events.",
    primaryDataDomains: ["Jobs", "Customers", "Schedules"],
    capabilities: ["Job sync", "Customer sync"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Service SMB fleets"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: true,
    mappingObjectTypes: ["jobs", "customers", "sites"],
  },
  {
    key: "housecall_pro",
    provider: null,
    displayName: "Housecall Pro",
    category: "dispatch_field_service",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned field service connector for technician and job workflow coverage.",
    primaryDataDomains: ["Jobs", "Technicians", "Schedules"],
    capabilities: ["Dispatch sync", "Status updates"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Distributed service teams"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: true,
    mappingObjectTypes: ["jobs", "operators", "customers", "sites"],
  },
  {
    key: "service_fusion",
    provider: null,
    displayName: "Service Fusion",
    category: "dispatch_field_service",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned connector for dispatch operations and field execution updates.",
    primaryDataDomains: ["Dispatch", "Jobs", "Technician status"],
    capabilities: ["Dispatch sync", "Work status ingest"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Field operations teams"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: true,
    mappingObjectTypes: ["jobs", "operators", "sites"],
  },
  {
    key: "quickbooks",
    provider: "quickbooks",
    displayName: "QuickBooks",
    category: "erp_accounting",
    providerType: "native",
    connectorType: "accounting",
    authType: "oauth",
    status: "available",
    description: "Financial and job revenue data for contribution and profitability insights.",
    primaryDataDomains: ["Revenue", "Job costing", "Customer financials"],
    capabilities: ["Revenue sync", "Cost context", "Historical financial coverage"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Operational profitability", "Executive reporting"],
    version: "v1.0",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["jobs", "customers"],
  },
  {
    key: "sage",
    provider: null,
    displayName: "Sage",
    category: "erp_accounting",
    providerType: "future",
    connectorType: "accounting",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned ERP/accounting connector for enterprise financial operations.",
    primaryDataDomains: ["Revenue", "Cost centers", "Financial dimensions"],
    capabilities: ["Financial sync", "Job costing context"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Enterprise finance alignment"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["jobs", "customers", "branches"],
  },
  {
    key: "acumatica",
    provider: null,
    displayName: "Acumatica",
    category: "erp_accounting",
    providerType: "future",
    connectorType: "accounting",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned ERP integration for project, cost, and revenue operational context.",
    primaryDataDomains: ["Revenue", "Project costs", "Branch financials"],
    capabilities: ["ERP sync", "Financial coverage"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Multi-entity operations"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["jobs", "customers", "branches"],
  },
  {
    key: "vista",
    provider: null,
    displayName: "Vista",
    category: "erp_accounting",
    providerType: "future",
    connectorType: "accounting",
    authType: "api_key",
    status: "coming_soon",
    description: "Planned Viewpoint Vista connector for enterprise project accounting.",
    primaryDataDomains: ["Project financials", "Revenue", "Cost tracking"],
    capabilities: ["Financial ingest", "Project profitability context"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Construction/contractor enterprises"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["jobs", "customers", "branches"],
  },
  {
    key: "foundation",
    provider: null,
    displayName: "Foundation",
    category: "erp_accounting",
    providerType: "future",
    connectorType: "accounting",
    authType: "api_key",
    status: "coming_soon",
    description: "Planned Foundation ERP connector for financial and labor cost alignment.",
    primaryDataDomains: ["Revenue", "Labor cost", "Project cost"],
    capabilities: ["Accounting sync", "Cost coverage"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Contracting operations"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["jobs", "operators", "customers"],
  },
  {
    key: "microsoft_dynamics",
    provider: null,
    displayName: "Microsoft Dynamics",
    category: "erp_accounting",
    providerType: "future",
    connectorType: "accounting",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned Microsoft Dynamics connector for enterprise operational finance coverage.",
    primaryDataDomains: ["ERP data", "Revenue", "Operational costs"],
    capabilities: ["ERP ingest", "Financial context"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Microsoft-centric enterprises"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["jobs", "customers", "branches"],
  },
  {
    key: "netsuite",
    provider: null,
    displayName: "NetSuite",
    category: "erp_accounting",
    providerType: "future",
    connectorType: "accounting",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned NetSuite integration for enterprise profitability and reporting context.",
    primaryDataDomains: ["Revenue", "Financial dimensions", "Operational cost"],
    capabilities: ["ERP sync", "Financial reporting context"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Enterprise multi-entity orgs"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["jobs", "customers", "branches"],
  },
  {
    key: "adp",
    provider: null,
    displayName: "ADP",
    category: "hr_workforce",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned HR/payroll connector for workforce availability and labor planning.",
    primaryDataDomains: ["Labor availability", "Payroll signals", "Certifications"],
    capabilities: ["Workforce sync", "Labor context"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Labor-sensitive operations"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["operators", "branches"],
  },
  {
    key: "paylocity",
    provider: null,
    displayName: "Paylocity",
    category: "hr_workforce",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned connector for workforce planning and payroll-backed labor signals.",
    primaryDataDomains: ["Labor", "Availability", "HR profiles"],
    capabilities: ["Operator sync", "Labor planning context"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Operational workforce planning"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["operators", "branches"],
  },
  {
    key: "paychex",
    provider: null,
    displayName: "Paychex",
    category: "hr_workforce",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned HR connector for payroll and labor availability signals.",
    primaryDataDomains: ["Labor", "Payroll", "Workforce profile"],
    capabilities: ["Labor context", "Availability sync"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Payroll-connected operations"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["operators", "branches"],
  },
  {
    key: "ukg",
    provider: null,
    displayName: "UKG",
    category: "hr_workforce",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned workforce connector for operator scheduling and labor intelligence.",
    primaryDataDomains: ["Scheduling", "Labor availability", "Certifications"],
    capabilities: ["Workforce ingest", "Labor planning"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Enterprise workforce orchestration"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["operators", "branches"],
  },
  {
    key: "salesforce",
    provider: null,
    displayName: "Salesforce",
    category: "crm",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned CRM connector for customer/account context in operational workflows.",
    primaryDataDomains: ["Accounts", "Contacts", "Opportunities"],
    capabilities: ["Customer sync", "Account context"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Enterprise customer operations"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: true,
    mappingObjectTypes: ["customers", "sites", "jobs"],
  },
  {
    key: "hubspot",
    provider: null,
    displayName: "HubSpot",
    category: "crm",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned CRM integration for customer and account-level operational alignment.",
    primaryDataDomains: ["Customers", "Contacts", "Deals"],
    capabilities: ["Customer ingest", "CRM context"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Revenue + operations alignment"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: true,
    mappingObjectTypes: ["customers", "sites", "jobs"],
  },
  {
    key: "microsoft_crm",
    provider: null,
    displayName: "Microsoft CRM",
    category: "crm",
    providerType: "future",
    connectorType: "fleet_operations",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned Microsoft CRM connector for account and customer operational context.",
    primaryDataDomains: ["Accounts", "Contacts", "Opportunities"],
    capabilities: ["Account sync", "Customer context"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Microsoft enterprise stack"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: true,
    mappingObjectTypes: ["customers", "sites", "jobs"],
  },
  {
    key: "csv",
    provider: "csv_manual",
    displayName: "CSV Import",
    category: "operational_data_sources",
    providerType: "native",
    connectorType: "import",
    authType: "none",
    status: "available",
    description: "CSV ingestion for operational entity onboarding and historical data backfill.",
    primaryDataDomains: ["Branches", "Trucks", "Operators", "Jobs", "Customers", "Sites"],
    capabilities: ["Template-driven import", "Validation", "Mapping templates"],
    syncDirection: "inbound",
    connectionComplexity: "low",
    recommendedFor: ["Initial onboarding", "Historical backfill"],
    version: "v1.0",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["branches", "trucks", "operators", "jobs", "customers", "sites", "equipment"],
  },
  {
    key: "excel",
    provider: null,
    displayName: "Excel",
    category: "operational_data_sources",
    providerType: "future",
    connectorType: "import",
    authType: "none",
    status: "coming_soon",
    description: "Planned Excel-native ingestion for operational spreadsheets and templates.",
    primaryDataDomains: ["Operational records", "Historical loads"],
    capabilities: ["Spreadsheet import", "Template mapping"],
    syncDirection: "inbound",
    connectionComplexity: "low",
    recommendedFor: ["Spreadsheet-first teams"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["branches", "trucks", "operators", "jobs", "customers", "sites", "equipment"],
  },
  {
    key: "rest_api",
    provider: "rest_api",
    displayName: "REST API",
    category: "operational_data_sources",
    providerType: "custom",
    connectorType: "rest_ingest",
    authType: "bearer_token",
    status: "available",
    description: "Unified REST ingestion endpoint for tenant-safe operational data exchange.",
    primaryDataDomains: ["Jobs", "Trucks", "Operators", "Customers", "Sites"],
    capabilities: ["Authenticated ingest", "Validation hooks", "Mapping hooks"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Custom integrations", "Platform-to-platform ingest"],
    version: "v1.0",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["branches", "trucks", "operators", "jobs", "customers", "sites", "equipment"],
  },
  {
    key: "webhook",
    provider: "webhook",
    displayName: "Webhook",
    category: "operational_data_sources",
    providerType: "custom",
    connectorType: "webhook",
    authType: "webhook_secret",
    status: "available",
    description: "Inbound webhook event ingestion for near real-time operational updates.",
    primaryDataDomains: ["Job events", "Telematics events", "Operational updates"],
    capabilities: ["Signature verification", "Event logging", "Retry-ready processing"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Event-driven updates", "Near real-time integration"],
    version: "v1.0",
    supportsHistoricalSync: false,
    supportsPushWebhook: true,
    mappingObjectTypes: ["jobs", "trucks", "sites"],
  },
  {
    key: "sftp",
    provider: null,
    displayName: "SFTP",
    category: "operational_data_sources",
    providerType: "future",
    connectorType: "import",
    authType: "api_key",
    status: "coming_soon",
    description: "Planned secure file transfer channel for scheduled operational data drops.",
    primaryDataDomains: ["Batch file ingest", "Historical operational data"],
    capabilities: ["Scheduled file ingest", "Batch processing"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["Enterprise batch exchange"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["branches", "trucks", "operators", "jobs", "customers", "sites", "equipment"],
  },
  {
    key: "graphql",
    provider: null,
    displayName: "GraphQL",
    category: "operational_data_sources",
    providerType: "future",
    connectorType: "rest_ingest",
    authType: "bearer_token",
    status: "coming_soon",
    description: "Planned GraphQL ingestion channel for structured operational data synchronization.",
    primaryDataDomains: ["Operational entity graph", "Incremental updates"],
    capabilities: ["Graph query ingest", "Schema-aware mapping"],
    syncDirection: "inbound",
    connectionComplexity: "high",
    recommendedFor: ["API-first enterprises"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["branches", "trucks", "operators", "jobs", "customers", "sites", "equipment"],
  },
  {
    key: "custom_rest_connector",
    provider: null,
    displayName: "Custom REST Connector",
    category: "custom_integrations",
    providerType: "custom",
    connectorType: "rest_ingest",
    authType: "bearer_token",
    status: "coming_soon",
    description: "Planned templated custom REST connector for enterprise system onboarding.",
    primaryDataDomains: ["Custom operational payloads"],
    capabilities: ["Custom schema mapping", "Connector templates"],
    syncDirection: "bidirectional",
    connectionComplexity: "high",
    recommendedFor: ["Enterprise custom system landscapes"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: false,
    mappingObjectTypes: ["branches", "trucks", "operators", "jobs", "customers", "sites", "equipment"],
  },
  {
    key: "custom_webhook_connector",
    provider: null,
    displayName: "Custom Webhook",
    category: "custom_integrations",
    providerType: "custom",
    connectorType: "webhook",
    authType: "webhook_secret",
    status: "coming_soon",
    description: "Planned custom webhook templates for partner and customer event streams.",
    primaryDataDomains: ["Operational events", "Status updates"],
    capabilities: ["Custom event mapping", "Webhook templates"],
    syncDirection: "inbound",
    connectionComplexity: "medium",
    recommendedFor: ["Event-driven custom integrations"],
    version: "planned",
    supportsHistoricalSync: false,
    supportsPushWebhook: true,
    mappingObjectTypes: ["jobs", "trucks", "sites", "customers", "operators"],
  },
  {
    key: "future_sdk",
    provider: null,
    displayName: "Integration SDK",
    category: "custom_integrations",
    providerType: "future",
    connectorType: "rest_ingest",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned SDK for building certified enterprise connectors on Cornerstone.",
    primaryDataDomains: ["Custom operational domains"],
    capabilities: ["SDK templates", "Connector certification workflow"],
    syncDirection: "bidirectional",
    connectionComplexity: "high",
    recommendedFor: ["Strategic enterprise integration programs"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: true,
    mappingObjectTypes: ["branches", "trucks", "operators", "jobs", "customers", "sites", "equipment"],
  },
  {
    key: "future_event_bus",
    provider: null,
    displayName: "Operational Event Bus",
    category: "custom_integrations",
    providerType: "future",
    connectorType: "webhook",
    authType: "oauth",
    status: "coming_soon",
    description: "Planned event bus integration for enterprise-scale operational event exchange.",
    primaryDataDomains: ["Operational events", "Cross-system orchestration"],
    capabilities: ["Event streaming", "Durable event replay"],
    syncDirection: "bidirectional",
    connectionComplexity: "high",
    recommendedFor: ["Large enterprise ecosystems"],
    version: "planned",
    supportsHistoricalSync: true,
    supportsPushWebhook: true,
    mappingObjectTypes: ["jobs", "trucks", "operators", "customers", "sites", "branches"],
  },
] as const;

export function getConnectorDefinitionByKey(key: string): ConnectorDefinition | null {
  return CONNECTOR_CATALOG.find((connector) => connector.key === key) ?? null;
}

export function getConnectorDefinitionByProvider(
  provider: IntegrationProvider
): ConnectorDefinition | null {
  return CONNECTOR_CATALOG.find((connector) => connector.provider === provider) ?? null;
}
