/**
 * Fleet Intelligence product knowledge registry.
 * Used for "how does this work?" and "what does X mean?" — not as operational data source.
 */

export type FleetProductKnowledgeTopic = {
  id: string;
  title: string;
  keywords: string[];
  content: string;
  relatedScreen?: string;
};

export const FLEET_PRODUCT_KNOWLEDGE: FleetProductKnowledgeTopic[] = [
  {
    id: "command_center",
    title: "Fleet Command Center",
    keywords: ["command center", "operations center", "today's plan", "readiness"],
    relatedScreen: "/operations",
    content:
      "Fleet Command Center is your daily operational briefing. It surfaces utilization, contribution, revenue at risk, pending recommendations, and exceptions that need attention before dispatch. Use it to decide what to tackle first each morning.",
  },
  {
    id: "dispatch_workspace",
    title: "Dispatch Intelligence (Dispatch Workspace)",
    keywords: ["dispatch workspace", "dispatch intelligence", "dispatch board", "assign truck"],
    relatedScreen: "/dispatch",
    content:
      "Dispatch Intelligence is the live dispatch workspace. Review the mission briefing, job queue, truck lanes, and map. Accept or dismiss AI recommendations — humans approve every assignment. The map shows jobs, trucks, deadhead routes, and recommendation overlays.",
  },
  {
    id: "fleet_operations",
    title: "Fleet Operations",
    keywords: ["fleet operations", "live execution", "job ledger", "trucks registry"],
    content:
      "Fleet Operations covers live execution: trucks, operators, jobs, and sites. Use it to verify registry data, review job status, and investigate execution issues outside the dispatch board.",
  },
  {
    id: "recommendations",
    title: "Recommendations",
    keywords: ["recommendation", "recommend", "suggest truck", "why recommended"],
    content:
      "Recommendations are generated by the fleet recommendation engine using today's operational snapshot — jobs, truck locations, branch capacity, telematics freshness, travel estimates, and contribution impact. They are suggestions only; dispatchers accept or dismiss them on the Dispatch board.",
  },
  {
    id: "fleet_performance",
    title: "Fleet Performance",
    keywords: ["fleet performance", "branch contribution", "profitability", "performance report"],
    relatedScreen: "/reports/operations",
    content:
      "Fleet Performance shows branch, truck, and operator contribution over a selected date range using utilization_daily marts. Use it to compare branches, find deadhead and idle cost drivers, and rank trucks and operators by contribution.",
  },
  {
    id: "integrations",
    title: "Integrations",
    keywords: ["integration", "connect", "samsara", "telematics", "webhook"],
    relatedScreen: "/settings/integrations",
    content:
      "Integrations feed trucks, jobs, telematics, and operators into Cornerstone. Connection health reflects status, last sync time, and error state. Stale or missing feeds reduce recommendation confidence. Configure connections under Settings → Integrations or the Implementation Center.",
  },
  {
    id: "exceptions",
    title: "Operational Exceptions",
    keywords: ["exception", "blocker", "attention", "at risk"],
    content:
      "Exceptions are rule-detected operational issues: unassigned urgent jobs, capacity overload, offline GPS, late jobs, integration errors, and revenue at risk. They appear on Command Center and Dispatch briefing strips.",
  },
  {
    id: "deadhead",
    title: "Deadhead",
    keywords: ["deadhead", "empty miles", "non-revenue miles", "travel waste"],
    content:
      "Deadhead is non-revenue travel — miles driven without a billable job at the destination. Cornerstone estimates deadhead from truck position to job site when assigning work. High deadhead increases fuel cost and reduces utilization. Fleet Performance tracks deadhead cost by branch and truck.",
  },
  {
    id: "contribution",
    title: "Contribution",
    keywords: ["contribution", "contribution margin", "profit", "margin"],
    content:
      "Contribution is revenue minus variable operating costs (labor, fuel, deadhead, idle, overtime) for a job, truck, branch, or day. It is the primary profitability metric in Fleet Intelligence — not just on-time performance.",
  },
  {
    id: "revenue_at_risk",
    title: "Revenue at risk",
    keywords: ["revenue at risk", "revenue risk", "unassigned revenue"],
    content:
      "Revenue at risk is estimated revenue from jobs that are unassigned or at risk of slipping today. It helps dispatchers prioritize which jobs to assign first.",
  },
  {
    id: "confidence",
    title: "Recommendation confidence",
    keywords: ["confidence", "low confidence", "high confidence", "why confidence"],
    content:
      "Confidence reflects how reliable a recommendation is given data quality: telematics freshness, GPS availability, branch capacity certainty, travel estimate quality, and engine score. Low confidence means verify truck location, integration sync, or job geocoding before accepting.",
  },
  {
    id: "operational_snapshot",
    title: "Operational snapshot",
    keywords: ["snapshot", "board date", "stale recommendation"],
    content:
      "Each recommendation is tied to an operational snapshot (dispatch board date and data hash). If trucks move, jobs change, or syncs fail, recommendations may expire or recalculate. Always review freshness before accepting.",
  },
  {
    id: "hard_constraints",
    title: "Hard constraints",
    keywords: ["hard constraint", "ineligible", "cannot assign"],
    content:
      "Hard constraints block assignment: truck type mismatch, truck unavailable, operator conflict, or branch capacity hard limits. The engine will not recommend trucks that violate hard constraints.",
  },
  {
    id: "soft_scoring",
    title: "Soft scoring factors",
    keywords: ["soft score", "scoring", "factors", "tradeoff"],
    content:
      "Soft scoring ranks eligible trucks by travel impact, utilization balance, branch capacity, telematics freshness, profitability impact, labor/overtime risk, and SLA risk. The highest-scoring eligible truck is recommended; alternatives show tradeoffs.",
  },
  {
    id: "recommendation_lifecycle",
    title: "Recommendation lifecycle",
    keywords: ["lifecycle", "expired", "pending", "accepted", "dismissed"],
    content:
      "Recommendations move through pending → displayed → accepted or dismissed. They expire after a TTL if not acted on. Accepting applies the truck assignment; dismissing records the decision for learning and ROI tracking.",
  },
  {
    id: "data_freshness",
    title: "Data freshness",
    keywords: ["freshness", "stale gps", "stale sync", "offline"],
    content:
      "Data freshness measures how current telematics, job, and integration data is. Stale GPS or sync delays reduce recommendation quality. Check Integration health and truck telematics status on Dispatch.",
  },
  {
    id: "integration_health",
    title: "Integration health",
    keywords: ["integration health", "unhealthy", "sync stale", "connection error"],
    content:
      "Integration health is healthy, warning, or error based on connection status, last sync time, and poll interval. Warning usually means no sync yet or sync is stale. Error means the connection failed — recommendations may use incomplete data.",
  },
  {
    id: "baseline",
    title: "Baseline",
    keywords: ["baseline", "implementation baseline"],
    relatedScreen: "/implementation/baseline",
    content:
      "Baseline establishes your starting operational metrics during implementation — utilization, contribution, and deadhead benchmarks — so Fleet Performance comparisons are meaningful.",
  },
  {
    id: "implementation_center",
    title: "Implementation Center",
    keywords: ["implementation", "onboarding", "readiness", "imports", "connections"],
    relatedScreen: "/implementation",
    content:
      "Implementation Center guides connections, imports, baseline, and readiness checks before relying on AI recommendations. Complete connections and data imports before expecting full recommendation coverage.",
  },
  {
    id: "recommendation_engine",
    title: "How recommendations choose trucks",
    keywords: ["how does", "choose truck", "engine", "calculated", "algorithm"],
    content:
      "The recommendation engine evaluates eligible trucks for each unassigned or improvable job. It applies hard constraints first, then scores candidates on travel, utilization, capacity, telematics freshness, and contribution impact. The top candidate becomes the recommendation; alternatives are stored for explainability. Engine output is deterministic for a given snapshot — the copilot explains it but does not change scores.",
  },
  {
    id: "connect_samsara",
    title: "Connecting Samsara",
    keywords: ["connect samsara", "samsara setup", "how do i connect samsara"],
    relatedScreen: "/settings/integrations",
    content:
      "To connect Samsara: go to Settings → Integrations (or Implementation → Connections), add a Samsara connection, enter API credentials provided by your Samsara admin, and run an initial sync. Verify last sync time and that truck telematics show online on Dispatch.",
  },
  {
    id: "live_execution_screen",
    title: "Reviewing live execution",
    keywords: ["live execution", "review execution", "what screen"],
    content:
      "For live execution use Dispatch Intelligence (/dispatch) for assignments and the map, Fleet Command Center (/operations) for today's briefing, and Fleet Performance (/reports/operations) for contribution and deadhead trends.",
  },
];

export function searchFleetProductKnowledge(query: string, limit = 3): FleetProductKnowledgeTopic[] {
  const q = query.toLowerCase();
  const scored = FLEET_PRODUCT_KNOWLEDGE.map((topic) => {
    let score = 0;
    if (q.includes(topic.id.replace(/_/g, " "))) score += 5;
    for (const kw of topic.keywords) {
      if (q.includes(kw.toLowerCase())) score += 3;
    }
    for (const word of q.split(/\s+/)) {
      if (word.length < 3) continue;
      if (topic.title.toLowerCase().includes(word)) score += 1;
      if (topic.content.toLowerCase().includes(word)) score += 0.5;
    }
    return { topic, score };
  })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map((x) => x.topic);
}

export function getFleetProductKnowledgeById(id: string): FleetProductKnowledgeTopic | undefined {
  return FLEET_PRODUCT_KNOWLEDGE.find((t) => t.id === id);
}
